### ISSUE TITLE
FEATURE REQUEST: Develop a 'Continue with Google' button in Login.js component.

### ISSUE THREAD

**Issue by ani1609** [ani1609/Spendwise#180]
<img width="295" alt="Screenshot 2023-12-11 at 8 31 04 PM" src="https://github.com/ani1609/Spendwise/assets/89239354/4baf0018-deee-4c9e-ae30-47d29fabf9f7">

Go to client/src/components/Login.js and add a 'Continue with Google' button below the login button.

**Description:**
We're looking to enhance our user authentication experience on the frontend by adding a "Continue with Google" button. For this task, we are solely focusing on the UI implementation, and no backend logic is required at this stage.

**Tasks:**
- [ ] Create the "Continue with Google" button UI on the login/registration page.
- [ ] Ensure the button has a visually appealing and consistent design.
- [ ] Implement any necessary styling or animations for a seamless user experience.

**Additional Information:**
- The frontend is developed using React

**Notes:**
- Please only work on the UI aspects; no authentication logic build is needed at this point.
- Keep the implementation clean, modular, and well-documented.
- Test thoroughly to ensure a polished user interface.

**Comment by SHIVAA17** [comment]
@ani1609  hello Mentor, Can I start working on this issue.

**Comment by ani1609** [comment]
@SHIVAA17 sure.
